export const FETCH_CLIENT_LIST_ACTION = 'FETCH_CLIENT_LIST_ACTION';
export const FETCH_CLIENT_PROFILE_ACTION = 'FETCH_CLIENT_PROFILE_ACTION';

export const UPDATE_CLIENT_ACTION = 'UPDATE_CLIENT_ACTION';
export const RENEW_SUBSCRIPTION_ACTION = 'RENEW_SUBSCRIPTION_ACTION';

export const EXPIRED_FILTER = 'expired';
export const ACTIVE_FILTER = 'active';
export const INACTIVE_FILTER = 'inactive';
export const NAME_FILTER = 'name';